local keymap = vim.keymap
local s_opts = {silent = true, noremap = true}
local opts = {silent = true, noremap = true}
keymap.set('n', '<leader>k', [[:bnext<CR>]], s_opts)
keymap.set('n', '<leader>j', [[:bprev<CR>]], s_opts)
keymap.set('n', '<leader>w', [[:w!<CR>]],    s_opts)
keymap.set('t', '<C-[>',     [[<C-\><C-n>]], s_opts)
keymap.set('n', 'j',         [[gj]],         s_opts)
keymap.set('n', 'k',         [[gk]],         s_opts)
keymap.set('n', 'gj',        'j',            s_opts)
keymap.set('n', 'gk',        'k',            s_opts)
keymap.set('n', 'q',         '<Nop>',        s_opts)
keymap.set('i', '<UP>',      '<Nop>',        opts)
keymap.set('i', '<DOWN>',    '<Nop>',        opts)
keymap.set('i', '<RIGHT>',   '<Nop>',        opts)
keymap.set('i', '<LEFT>',    '<Nop>',        opts)
keymap.set('i', '<S-UP>',    '<Nop>',        opts)
keymap.set('i', '<S-DOWN>',  '<Nop>',        opts)
keymap.set('i', '<S-RIGHT>', '<Nop>',        opts)
keymap.set('i', '<S-LEFT>',  '<Nop>',        opts)
keymap.set('n', 'Q',         'q',            opts)
--keymap.set('c', '<C-a>',     '<Home>',       s_opts)
--keymap.set('c', '<C-f>',     '<Right>',      s_opts)
--keymap.set('c', '<C-b>',     '<Left>',       s_opts)
