set -g prefix C-q
unbind C-b

set -g mouse on
set -g history-limit 1000
set -g status on
set -g status-position bottom
set -g status-style 'bg=default,fg=colour250'
set -g status-left-length 20
set -g status-left '#(if [ -f ~/.machine-name ]; then cat ~/.machine-name; else hostname -s; fi) '
set -g status-right ''
