shell = "zsh"

[plugins]

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.git-open]
github = "paulirish/git-open"

[plugins.history-search-multi-word]
github = "zdharma/history-search-multi-word"

[plugins.dotfiles]
local = "~/dotfiles/zsh"
use = ["*.zsh"]

[plugins.zshrc-local]
inline = "if [ ! -f ~/.zshrc.local ]; then touch ~/.zshrc.local; fi; source ~/.zshrc.local"
