
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'mhinz/neovim-remote'


# [[plugins]]
# repo = 'tomasr/molokai'
# 
# hook_add = '''
#     set background=dark
#     au MyAutoCmd VimEnter * nested colorscheme molokai
# '''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'inkarkat/vim-SyntaxRange'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-surround'

# [[plugins]]
# repo = 'neovim/nvim-lsp'
# hook_add = '''
# :packadd nvim_lsp
# lua << EOF
# require'nvim_lsp'.ccls.setup{}
# EOF
# '''

# lightline
[[plugins]]
repo = 'powerline/powerline-fonts'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
            \ 'colorscheme': 'molokai',
            \ 'mode_map': {'c': 'NORMAL'},
            \ 'active': {
            \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'filename' ] ]
            \ },
            \ 'tabline': {
            \   'left': [ [ 'test' , 'tabs' ] ],
            \   'right': [ [ 'close' ] ]
            \ },
            \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
            \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" },
            \ 'component': {
            \   'test': 'Hello, world'
            \ },
            \ 'component_function': {
            \   'modified': 'LightlineModified',
            \   'readonly': 'LightlineReadonly',
            \   'fugitive': 'LightlineFugitive',
            \   'filename': 'LightlineFilename',
            \   'fileformat': 'LightlineFileformat',
            \   'filetype': 'LightlineFiletype',
            \   'fileencoding': 'LightlineFileencoding',
            \   'mode': 'LightlineMode'
            \ }
            \ }
    
    function! LightlineModified()
      return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
    endfunction
    
    function! LightlineReadonly()
      return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
    endfunction
    
    function! LightlineFilename()
      return ('' != LightlineReadonly() ? LightlineReadonly() . ' ' : '') .
            \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
            \  &ft == 'vimshell' ? vimshell#get_status_string() :
            \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
            \ ('' != LightlineModified() ? ' ' . LightlineModified() : '')
    endfunction
    
    function! LightlineFugitive()
      if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
        return fugitive#head()
      else
        return ''
      endif
    endfunction
    
    function! LightlineFileformat()
      return winwidth(0) > 70 ? &fileformat : ''
    endfunction
    
    function! LightlineFiletype()
      return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
    endfunction
    
    function! LightlineFileencoding()
      return winwidth(0) > 70 ? (&fenc !=# '' ? &fenc : &enc) : ''
    endfunction
    
    function! LightlineMode()
      return winwidth(0) > 60 ? lightline#mode() : ''
    endfunction
'''


# neoterm
[[plugins]]
repo = 'kassio/neoterm'

# neosnippet
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'
#
#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#hook_add = '''
#    imap <C-k>     <Plug>(neosnippet_expand_or_jump)
#    smap <C-k>     <Plug>(neosnippet_expand_or_jump)
#    xmap <C-k>     <Plug>(neosnippet_expand_target)
#
#    smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
#    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
#
#    if has('conceal')
#        set conceallevel=2 concealcursor=niv
#    endif
#'''
#


