
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'mhinz/neovim-remote'


[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'inkarkat/vim-SyntaxRange'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nnoremap <leader>gc :Gcommit<CR>
    nnoremap <leader>ga :Gwrite<CR>
    nnoremap <leader>gp :Git push<CR>
'''

# lightline
[[plugins]]
repo = 'powerline/powerline-fonts'

[[plugins]]
repo = 'hoob3rt/lualine.nvim'
hook_add = '''
    au VimEnter * nested lua require('nitom/lualineconfig')
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# terminal
[[plugins]]
repo = 'kassio/neoterm'

# quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = {
    \
    \   '_': {
    \       'outputter': 'message'
    \   },
    \   'tex': {
    \       'command': 'latexmk',
    \       'outputter': 'error',
    \       'outputter/error/success': 'null',
    \       'outputter/error/error': 'buffer',
    \       'outputter/buffer/split': '""',
    \       'exec': ['%c -gg -pdfdvi %s', '%c -c %s', 'xdg-open %s:r.pdf'],
    \       'hook/sweep/files': [
    \                      '%S:p:r.aux',
    \                      '%S:p:r.bbl',
    \                      '%S:p:r.blg',
    \                      '%S:p:r.dvi',
    \                      '%S:p:r.fdb_latexmk',
    \                      '%S:p:r.fls',
    \                      '%S:p:r.log',
    \                      '%S:p:r.out'
    \                      ],
    \   },
    \   'cs': {
    \       'command': 'mcs',
    \       'cmdopt': '-pkg:dotnet'
    \   },
    \}
'''









